name: test

on:
  push:
  pull_request:
    branches:
    - master

jobs:
  tests:
    name: Running tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: project_portal_test
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, dom, fileinfo, mysql
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Install composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Setup environment variables
        run: php -r "copy('.env.example', '.env');"

      - name: Clear Config
        run: php artisan config:clear

      - name: Setup, migrate and seed
        run: |
          php artisan key:generate &&
          php artisan migrate:fresh --env=testing --database=testing --seed --seeder=TestSeeder &&
          php artisan passport:install
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Run tests
        run: php artisan test
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
